name: rtext
version: 0.10.0
git: https://github.com/mthiede/rtext.git
summary: Ruby Textual Modelling
email: martin dot thiede at gmx de
homepage: http://ruby-gen.org
description: RText can be used to derive textual languages from an RGen metamodel with very little effort.
authors: [Martin Thiede]
dependencies:
  http://rubygems.org:
    - {name: rgen,     version: ['>= 0.9.0', '< 0.10']}
    - {name: filelock, version: ['>= 1.1.1', '< 1.2']}
rdoc_options: [--main, README.rdoc, -x, test]
extra_rdoc_files: [README.rdoc, CHANGELOG, MIT-LICENSE, RText_Users_Guide, RText_Protocol]
encrypt_sources: false
